#!/bin/bash
# Based on
# https://www.digitalocean.com/community/tutorials/how-to-create-an-ssl-certificate-on-nginx-for-ubuntu-14-04
# and
# https://gist.github.com/jessedearing/2351836

if [ -r nginx/localhost.key -o -r nginx/localhost.crt ]; then
  echo "Certs already exist in nginx"
  exit 0
fi

openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
  -keyout nginx/localhost.key \
  -out nginx/localhost.crt <<EOT
UK
Bristol
Bristol
My project
Development
localhost

EOT
