#!/bin/bash

HTPASSWD=$(which htpasswd 2>/dev/null)
APG=$(which apg 2>/dev/null)
VIRTUALENV=$(which virtualenv 2>/dev/null)

if [ -z "$HTPASSWD" ]; then
  echo Install apache2-utils
  exit 1
fi
if [ -z "$APG" ]; then
  echo Install apg
  exit 1
fi
if [ -z "$VIRTUALENV" ]; then
  echo Install python-virtualenv
  exit 1
fi

set -e

output=nginx/htpasswd
if [ -f $output ]; then
  echo "htpasswd already exists in nginx"
  exit 0
fi

# Use the Python haikunator module to provide a more friendly username.
venv=haikunator-venv
if [ ! -d $venv ]; then
  $VIRTUALENV $venv
  source $venv/bin/activate
  pip install haikunator
else
  source $venv/bin/activate
fi

#uname=$(apg -n 1 -M C -m 12)
uname=$(python ./generate-http-username)
pword=$(apg -n 1 -M SNCL -m 16) # but note that crypt only use first 8 chars
echo "$uname $pword" > password.txt
htpasswd -b -c $output "$uname" "$pword"

